cafe/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# URLconf for the McFater Cafe app

app_name = 'cafe'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('contact/', views.contact, name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('login/', auth_views.LoginView.as_view(template_name="cafe/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update-profile')
]

mcfatter/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path('', include('cafe.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from tinymce import models as tinymce_models


# Models for the cafe app


class Category(models.Model):
    title = models.CharField(max_length=50, db_index=True)
    used_for = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class BlogPostImage(models.Model):
    image = models.ImageField(upload_to='media/images/cafe/blog')

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def __str__(self):
        return self.image.name





class BlogPost(models.Model):
    post_title = models.CharField(max_length=50)
    post_text = tinymce_models.HTMLField(max_length=10000)
    pub_date = models.DateTimeField('date published')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    images = models.ManyToManyField(BlogPostImage, blank=True)

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        now = timezone.localtime(timezone.now())
        return now - datetime.timedelta(days=7) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class CafeProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name="cafeprofile")
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    birth_date = models.DateField('birth_date', blank=True, null=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    def recent_order(self):
        return Order.objects.filter(user=self.pk)[:1].get()

    @receiver(post_save, sender=User)
    def ensure_cafeprofile_exists(sender, **kwargs):
        if kwargs.get('created', False):
            CafeProfile.objects.get_or_create(user=kwargs.get('instance'))


class MealType(models.Model):
    name = models.CharField(max_length=50, db_index=True)

    def __str__(self):
        return self.name


class Menu(models.Model):
    location_name = models.CharField(max_length=50, db_index=True)

    def has_special_today(self):
        for special in Specials.objects.filter(location=1):
            if special.is_special_today():
                return True

        return False

    def get_special(self):
        for special in Specials.objects.filter(location=1):
            if special.is_special_today():
                return special

    def __str__(self):
        return self.location_name

class Specials(models.Model):
    special = models.CharField(max_length=50)
    soup = models.CharField(max_length=50)
    date = models.DateField()
    location = models.ForeignKey(Menu, on_delete=models.CASCADE, default=1)

    class Meta:
        verbose_name_plural = "specials"

    def is_special_today(self):
        return self.date == timezone.localtime(timezone.now()).date()

    def __str__(self):
        return "{} {}, {} - Special: {}, Soup: {}".format(self.date.month,self.date.day,self.date.year,self.special,self.soup)

class MenuItem(models.Model):
    name = models.CharField(max_length=50)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, default=1)
    type = models.ForeignKey(MealType, on_delete=models.CASCADE, default=1)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    description = models.TextField(max_length=1000)

    # Nutritional fields
    calories = models.IntegerField(default=0)
    fat = models.IntegerField(default=0, blank=True, null=True)
    sat_fat = models.IntegerField(default=0, blank=True, null=True)
    trans_fat = models.IntegerField(default=0, blank=True, null=True)
    protein = models.IntegerField(default=0, blank=True, null=True)
    carbs = models.IntegerField(default=0, blank=True, null=True)
    dietary_fiber = models.IntegerField(default=0, blank=True, null=True)
    sugar = models.IntegerField(default=0, blank=True, null=True)
    sodium = models.IntegerField(default=0, blank=True, null=True)
    cholesterol = models.IntegerField(default=0, blank=True, null=True)
    potassium = models.IntegerField(default=0, blank=True, null=True)

    image = models.ImageField(upload_to='media/images/cafe/menu', blank=True, null=True)
    available = models.BooleanField(default=True)
    extra_options = models.CharField(max_length=100, blank=True, null=True)
    multiple_sizes = models.BooleanField(default=False)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def is_entree(self):
        return self.type.name == 'Entree'

    def is_side(self):
        return self.type.name == 'Side'

    def is_special_today(self):
        return self.name.lower() == Specials.objects.get(date=timezone.localtime(timezone.now()).date()).special.lower() or self.name.lower() == Specials.objects.get(date=timezone.localtime(timezone.now()).date()).soup.lower()

    def __str__(self):
        return self.name


class Order(models.Model):
    time_placed = models.TimeField('time placed')
    is_ready = models.BooleanField(default=False)
    order_for = models.CharField(max_length=50)
    pickup_time = models.DateTimeField('pickup time', blank=True, null=True)
    user = models.ForeignKey(CafeProfile, on_delete=models.CASCADE, blank=True, null=True)
    items = models.TextField(max_length=5000)
    total = models.DecimalField(max_digits=4, decimal_places=2)
    instructions = models.TextField(max_length=5000, blank=True, null=True)

    def __str__(self):
        return self.items


class Ticket(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    ticket_text = models.TextField(max_length=5000)
    user = models.ForeignKey(CafeProfile, on_delete=models.CASCADE, blank=True, null=True)
    complete = models.BooleanField(default=False)
    date = models.DateTimeField('time received')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.subject

    def is_complete(self):
        return self.complete

    is_complete.admin_order_field = 'subject'
    is_complete.boolean = True
    is_complete.short_description = 'Is ticket complete?'

cafe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import CafeProfile, Category

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    birth_date = forms.DateField()
    phone_number = forms.CharField(max_length=15)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'birth_date', 'phone_number')


class ContactForm(forms.Form):
    first_name = forms.CharField(label='', max_length=30, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(label='', max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    phone_number = forms.CharField(label='', max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Phone number'}))
    email = forms.EmailField(label='', required=True, max_length=254, widget=forms.TextInput(attrs={'placeholder': 'Email address'}))
    category = forms.ModelChoiceField(queryset=Category.objects.filter(used_for='Support'))
    subject = forms.CharField(label='', required=True, max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Subject'}))
    comments = forms.CharField(label='', required=True, max_length=1000, widget=forms.TextInput(attrs={'placeholder': 'Questions, '
                                                                                                       'comments, or '
                                                                                                       'concerns',
                                                                                                       'id' : 'comments',}))

cafe/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import BlogPost, MenuItem, Ticket, Specials, Menu, Order
from django.utils import timezone
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, ContactForm
import json


# Views for the cafe app


# News / Home
# Models used: BlogPost
# BlogPost - Author, Category, Body, Title, Date


class IndexView(generic.ListView):
    template_name = 'cafe/index.html'
    context_object_name = 'home_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['cafe_specials'] = Specials.objects.all()
        context['cafe_menu_object'] = Menu.objects.filter(location_name__contains="Cafe")
        return context

    def get_queryset(self):
        return BlogPost.objects.filter(pub_date__lte=timezone.localtime(timezone.now()),
                                       category__title__contains="News").order_by('-pub_date')[:5]


# About
# Models used: BlogPost, TeamMembers
# TeamMember - Name, Image, Roles, Bio


class AboutView(generic.ListView):
    template_name = 'cafe/about.html'
    context_object_name = 'about_post_list'

    def get_queryset(self):
        return BlogPost.objects.filter(pub_date__lte=timezone.localtime(timezone.now()),
                                       category__title__contains="About").order_by('-pub_date')


# Menu
# Models used: Menu, MenuItem
# Menu - Location
# MenuItem - Name, Price, Calories, Protein, Carbohydates, Sugar, Fat
# Uses a JavaScript to add things to order


class MenuView(generic.ListView):
    template_name = 'cafe/menu.html'
    context_object_name = 'menu_item_list'

    def get_context_data(self, **kwargs):
        context = super(MenuView, self).get_context_data(**kwargs)
        context['cafe_menu_object'] = Menu.objects.filter(location_name__contains="Cafe")
        return context

    def get_queryset(self):
        return MenuItem.objects.all()


# Order / Cart
# Models used:
# View order via a JavaScript


class OrderView(generic.TemplateView):
    template_name = 'cafe/order.html'


# Confirm order
# Redirected to this view from order


def checkout(request):
    if request.method == 'POST':
        data = request.POST
        pickup_time_fixed = '{} {}'.format(timezone.localtime(timezone.now()).date(), data['pickupTime'])
        cart = json.loads(data['cart'])  # pass the json string here
        items = ''
        total = 0.0
        instructions = ''
        for item in cart:
            if items == '':
                items = '{}x {}'.format(item['qty'], item['item'])
                instructions = item['instructions']
            else:
                items = '{}; {}x {}'.format(items, item['qty'], item['item'])
                instructions = '{}; {}'.format(instructions, item['instructions'])
            total += float(item['price'])

        order = Order.objects.create(order_for=data['orderFor'], pickup_time=pickup_time_fixed,
                                     time_placed=timezone.localtime(timezone.now()), items=items, total=total,
                                     instructions=instructions)
        if request.user.is_authenticated:
            order.user = request.user.cafeprofile
        order.save()
    else:
        print('User tried to circumvent POST')
    return redirect('cafe:index')


# Submit a support ticket
# Validates and processes a ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ticket = Ticket.objects.create(first_name=data['first_name'], last_name=data['last_name'],
                                           phone_number=data['phone_number'], email=data['email'],
                                           subject=data['subject'],
                                           ticket_text=data['comments'], date=timezone.localtime(timezone.now()),
                                           category=data['category'])
            if request.user.is_authenticated:
                ticket.user = request.user.cafeprofile
            ticket.save()
            return redirect('cafe:index')
    else:
        if request.user.is_authenticated:
            user = request.user
            data = {'first_name': user.first_name,
                    'last_name': user.last_name,
                    'email': user.email,
                    'phone_number': user.cafeprofile.phone_number}
            form = ContactForm(initial=data)
        else:
            form = ContactForm()
    return render(request, 'cafe/contact.html', {'form': form})


# Generic view for Login page

class LoginView(generic.TemplateView):
    template_name = 'cafe/login.html'


# Registration page
# Validates and processes a SignUpForm

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()

            user.cafeprofile.birth_date = form.cleaned_data.get('birth_date')
            user.cafeprofile.phone_number = form.cleaned_data.get('phone_number')
            user.cafeprofile.save()
            user.save()

            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('cafe:index')
    else:
        form = SignUpForm()
    return render(request, 'cafe/register.html', {'form': form})


# Profile view, just renders the template

def profile(request):
    return render(request, 'cafe/profile.html')


# Update profile view, invoked from profile page

def update_profile(request):
    if request.method == 'POST':
        data = request.POST

        if request.user.is_authenticated:
            request.user.email = data['email']
            request.user.cafeprofile.phone_number = data['phonenumber']
            request.user.save()
            request.user.cafeprofile.save()

        return redirect('cafe:profile')
    else:
        return redirect('cafe:profile')

cafe/templates/cafe/about.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'cafe/about.css' %}">
{% endblock %}

{% block page_body %}
<div id="main">
		<div id="content">
            {% for post in about_post_list %}
			<article class="post">
				<header>
					<h2> {{ post.post_title }} </h2>
				</header>

				<footer>
					<p class="info"> From the McFatter Café Team: </p>
				</footer>

				<content>
					<p> {{ post.post_text|safe }} </p>

				</content>
			</article>
            {% endfor %}

	</div>
</div>
{% endblock %}

cafe/templates/cafe/base.html
<html>

<head>
{% block head %}
<title>McFatter Cafe</title>
{% endblock %}

    {% load static %}
	{% load cafe_extras %}
    <meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'cafe/base.css' %}">

{% block extra_styles %}

{% endblock %}
</head>

<body class="body" {% block bodytags %}{% endblock %}>

{% block header %}
<div id="top">

	<header class="main">
		<img src="{% static 'cafe/images/mtclogo.png' %}" alt="logo">

		<h1>McFatter Café</h1>

		<nav>
			<ul>
				<li> <a href="{% url 'cafe:index' %}"> Home </a> </li>
				<li> <a href="{% url 'cafe:about' %}"> About </a> </li>
				<li> <a href="{% url 'cafe:menu' %}"> Menu </a> </li>
				<li > <a href="{% url 'cafe:contact' %}"> Contact </a> </li>



				{% if user.is_authenticated %}

				<li style="float:right" id="navlogin"> <a href="{% url 'cafe:logout' %}"> Logout </a> </li>

				{% if user|has_group:"Developer" or user|has_group:"Cafe staff" %}
				<li style="float:right"> <a href="{% url 'admin:index' %}"> Admin </a> </li>
                {% endif %}
				<li style="float:right"> <a href="{% url 'cafe:profile' %}"> My Profile </a> </li>
				<li style="float:right"> <a href="{% url 'cafe:order' %}"> My Order </a> </li>
				{% else %}

				<li style="float:right" id="navlogin"> <a href="{% url 'cafe:register' %}"> Register </a> </li>
				<li style="float:right" id="navlogin"> <a href="{% url 'cafe:login' %}"> Login </a> </li>
				{% endif %}

			</ul>
		</nav>
	</header>

</div>
{% endblock %}



{% block page_body %}

{% endblock %}
</body>
<footer class="mainfooter">
	<p> Copyright &copy; &mdash; McFatter Programming Class of 2017 </p>
</footer>
</html>

cafe/templates/cafe/contact.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'cafe/contact.css' %}">
<script src="{% static 'cafe/scripts/alerts.js' %}"></script>
{% endblock %}

{% block page_body %}
<div id="area">

	<div id="contact">

		<h1>Contact Us</h1>
		<h2> If you have any issues and need assistance, please fill out the form. </h2>

		<form method="post" onsubmit="ticketSubmission()">
			{% csrf_token %}
			{% if form.errors %}
			{% for error in form.errors %}
			Please check your {{ error }}.
			{% endfor %}
			{% endif %}

			<ul>{% for field in form %}
			<li>{{ field }}</li>
				{% endfor %}
			</ul>

			<button type="submit" class="submit">Open ticket</button>

		</form>
		
		<h3> You should expect a response within 2-3 business days. </h3>

	</div>

</div>
{% endblock %}

cafe/templates/cafe/index.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'cafe/index.css' %}">
{% endblock %}

{% block page_body %}
<div id="main">
		<div id="content">

			{% for post in home_list %}
			<article class="newspost">
				<header>
					<h2> {{ post.post_title }} </h2>
				</header>

				<footer>
					<p class="info"> {{ post.pub_date }} </p>
				</footer>

				<content>
					<p> {{ post.post_text|safe }} </p>

				</content>
			</article>
			{% endfor %}
		</div>
	</div>

	<div class="topbar">
		<article>
			<h2> Special </h2>

			<p> Today's special is: </p>

			<p class="special"> {% with cafe_menu_object|first as cafe %}{% if cafe.has_special_today %}{{ cafe.get_special.special }}{% else %}No special posted.{% endif %}{% endwith %} </p>

		</article>
	</div>

	<div class="midbar">
		<article>
			<h2> Soup of the Day </h2>

			<p> Today's soup is: </p>

			<p class="special"> {% with cafe_menu_object|first as cafe %}{% if cafe.has_special_today %}{{ cafe.get_special.soup }}{% else %}No soup posted.{% endif %}{% endwith %} </p>
		</article>
	</div>

	<div class="botbar">
		<article>
			<h2> Social Media </h2>

			<a href="https://twitter.com/McFatter_Tech" target="_new"><img src="{% static 'cafe/images/twitterlogo.png' %}" alt="twitterlogo" id="smlogo"></a>

			<a href="https://www.facebook.com/McFatterTechnicalHighSchool" target="_new"><img src="{% static 'cafe/images/facebook.png' %}" alt="fblogo" id="smlogo"></a>

			<a href="https://www.instagram.com/mcfattertech" target="_new"><img src="{% static 'cafe/images/iglogo.png' %}" alt="iglogo" id="iglogo"></a>
		</article>
	</div>
{% endblock %}

cafe/templates/cafe/login.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link href="{% static 'cafe/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block page_body %}

<div id="main">

		<h2> Login </h2>

        <form method="post">

        	<div class="center">
				{% csrf_token %}
				{{ form.as_p }}

				<button type="submit" class="submit">Login</button>
			</div>

            <p class="center"> <a href="">Forgot username or password?</a> </p>
        </form>
</div>

{% endblock %}

cafe/templates/cafe/menu.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'cafe/menu.css' %}">
<script src="{% static 'cafe/scripts/cart.js' %}"></script>
{% endblock %}

{% block page_body %}
<div id="main">
		<div id="content">
			<article class="content">
				<header>
					<h2> Lunch Menu </h2>
				</header>

				<footer>
					<p class="info"> All nutritional information available upon clicking food images. </p>

					<p class="info"> <strong>Any special instructions for your order, such as toppings, cook temp, etc. can be included on the <a href="{% url 'cafe:order' %}">My Order</a> page.</strong> </p>

					<p class="info"> Jump to <a href="#entrees">entrees</a> or <a href="#sides">sides</a>.</p>
				</footer>

				{% with cafe_menu_object|first as cafe %}
				{% if cafe.has_special_today %}
				<h3 id="specials"> Daily Specials </h3> <!-- hide this if nothing has been posted -->
				{% endif %}
				{% endwith %}

				{% for menu_item in menu_item_list %}
				{% if menu_item.is_special_today %}
				<div>
				<img src="{% if menu_item.image %}{{ menu_item.image.url|default_if_none:'#' }}{% endif %}" class="food" alt="{{ menu_item.name }} image">

					<div class="hoverinfo"> <span>i</span>
					    	<p> 3
						    	<br /> lines
						    	<br /> of text
					    	</p>
				 	 </div>
				</div>

				<div class="specials">
					<p> <strong>{{ menu_item.name }}</strong> <i>...  {{ menu_item.calories }} kcal </i> </p>
					<p> {{ menu_item.description }} ... ${{ menu_item.price }}</p>
					{% if user.is_authenticated %}
					<input type="number" id="{{ menu_item.name }}Qty" min="1" max="5" placeholder="1" value="1">
					<button onclick="addToCart('{{ menu_item.name }}', document.getElementById('{{ menu_item.name }}Qty').value, {{ menu_item.price }})">Add to Order</button>
					{% endif %}
				</div>


				{% endif %}
                {% endfor %}


				<h3 id="entrees"> Entrées </h3>

                {% for menu_item in menu_item_list %}
				{% if menu_item.is_entree %}
				<div>
				<img src="{% if menu_item.image %}{{ menu_item.image.url|default_if_none:'#' }}{% endif %}" class="food" alt="{{ menu_item.name }} image">
				
					<div class="hoverinfo"> <span>i</span>
					    	<p> 3
						    	<br /> lines
						    	<br /> of text
					    	</p>
				 	 </div>
				</div>

				<div class="entree">
					<p> <strong>{{ menu_item.name }}</strong> <i>...  {{ menu_item.calories }} kcal </i> </p>
					<p> {{ menu_item.description }} ... ${{ menu_item.price }}</p>
					{% if user.is_authenticated %}
					<input type="number" id="{{ menu_item.name }}Qty" min="1" max="5" placeholder="1" value="1">
					<button onclick="addToCart('{{ menu_item.name }}', document.getElementById('{{ menu_item.name }}Qty').value, {{ menu_item.price }})">Add to Order</button>
					{% endif %}
				</div>


				{% endif %}
                {% endfor %}

				<p class="info"><a href="#">Back to top</a></p>

				<h3 id="sides"> Sides </h3>

				{% for menu_item in menu_item_list %}
				{% if menu_item.is_side %}
				<img src="{% if menu_item.image %}{{ menu_item.image.url|default_if_none:'#' }}{% endif %}" class="food" alt="{{ menu_item.name }} image">

				<div class="side">
					<p> <strong>{{ menu_item.name }}</strong> <i>...  {{ menu_item.calories }} kcal </i> </p>
					<p> {{ menu_item.description }} ... ${{ menu_item.price }}</p>
					{% if user.is_authenticated %}
					<input type="number" id="{{ menu_item.name }}Qty" min="1" max="5" placeholder="1" value="1">
					<button onclick="addToCart('{{ menu_item.name }}', document.getElementById('{{ menu_item.name }}Qty').value, {{ menu_item.price }})">Add to Order</button>
					{% endif %}
				</div>


				{% endif %}
				{% endfor %}


				<p class="info"><a href="#">Back to top</a></p>

			</article>
		</div>
	</div>
{% endblock %}

cafe/templates/cafe/order.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'cafe/order.css' %}">
<script src="{% static 'cafe/scripts/cart.js' %}"></script>
<script src="{% static 'cafe/scripts/alerts.js' %}"></script>
{% endblock %}

{% block bodytags %}
onload="setupTable()"
{% endblock %}

{% block page_body %}
<div id="order">

	<h2> My Order </h2>
	{% if user.is_authenticated %}

	<p style="text-align: center;">Add more items from the <a style="color: rgba(20,142,145,1);" href="{% url 'cafe:menu' %}">Menu</a> page.</p>
	<p style="text-align: center">Change quantity and specify instructions below (make sure to click update cart).</p>
	<p style="text-align: center">If specifying instructions for multiples of the same item, place each set of instructions on a new line.</p>

	<div id="cart">
	<form action="{% url 'cafe:checkout' %}" method="post" onsubmit="orderSubmission()">
		{% csrf_token %}

	<table id="orderTable">
			<tr>
				<th>Quantity</th>
				<th>Price</th>
				<th class="space">Item</th>
				<th>Instructions</th>
				<th><!-- Remove button space --></th>
			</tr>
		</table>

		<button type="button" class="button3" onclick="updateCartFromTable()">Update cart</button>
		<button type="button" class="button2" onclick="clearCart()">Clear cart</button>
		<!-- For Testing only
		<button class="button" onclick="cartAlert()">See cart array</button>
		-->
		<div class="center">
			<label>Who is this order for?</label>
			<input name="orderFor" type="text" value="{{ user.first_name }} {{ user.last_name }}" required>
			<br />
			<label>Pickup time</label>
			<input name="pickupTime" type="time" min="12:15:00" max="13:15:00" required> <!-- enforce this with javascript -->
		</div>

		<input type="hidden" name="cart" id="hiddenCart">

		<button type="submit" class="button" id="placeOrder">Place order</button> <!-- do not allow placing if cart is empty -->
	</form>
	</div>
	{% else %}
	You cannot place an order because you are not <a href="{% url 'cafe:login' %}">logged in</a>.
	{% endif %}
</div>

{% endblock %}

cafe/templates/cafe/profile.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link href="{% static 'cafe/profile.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block page_body %}

<div id="content">
	<div id="main">
		<h2> My Profile </h2>
		{% if user.is_authenticated %}
		

		<h6> Welcome, {{ user.first_name }}. Use this page if you need to update your contact information or view your orders. </h6>

		<div class="center">
			<form method="post" action="{% url 'cafe:update-profile' %}" onsubmit="alert('Profile has been updated');">
				{% csrf_token %}
			<h3> Phone Number: </h3>
			<input type="text" name="phonenumber" class="box" value="{{ user.cafeprofile.phone_number }}">
			<h3> Email Address </h3>
			<input type="text" name="email" class="box" value="{{ user.email }}">

			<button type="submit" class="submit">Update Profile</button>
			</form>
		</div>

		<h4> Recent Order </h4>

		<h5> Time Placed: </h5> {{ user.cafeprofile.recent_order.time_placed }}
		<h5> Pickup Time: </h5> {{ user.cafeprofile.recent_order.pickup_time }}
		<h5> Ready? </h5> {% if user.cafeprofile.recent_order.is_ready %}Yes{% else %}No{% endif %}
		<h5> Order Details: </h5> {{ user.cafeprofile.recent_order }}




		{% else %}
		You cannot view your profile because you are not <a href="{% url 'cafe:login' %}">logged in</a>.
		{% endif %}
	</div>
</div>


{% endblock %}

cafe/templates/cafe/register.html
{% extends 'cafe/base.html' %}

{% load static %}
{% block extra_styles %}
<link href="{% static 'cafe/signup.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block page_body %}

<div id="main">

	<h2> Sign Up </h2>

      <form method="post">

      	<div id="block">
		    {% csrf_token %}
		    {{ form.as_p }}

		    <button type="submit" class="submit">Register</button>
	    </div>

      </form>
</div>

{% endblock %}